trainer:
  name: Trainer
  num_epochs: 100
  output_dir: experiments/xray
  log_dir: logs

model:
  name: efficientnet_b3
  num_classes: 2

dataset:
  name: CustomDatasetLoader
  root: data
  batch_size: 4
  image_size: 512 
  num_workers: 16

optimizer:
  name: Adam
