trainer:
  name: Trainer
  num_epochs: 100
  output_dir: experiments/xray
  log_dir: logs

model:
  name: efficientnet_b0
  num_classes: 2

dataset:
  name: XRayDatasetLoader
  root: data
  batch_size: 1
  label_smoothing: 0.01
  mixup_prob: -1.0
  image_size: 24
  num_workers: 1

optimizer:
  name: Adam
